In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant('Hello, TensorFlow!')

In [3]:
sess = tf.Session()

In [4]:
print(sess.run(hello))

Hello, TensorFlow!


## Adding two vectors in TensorFlow


In [21]:
import tensorflow as tf

with tf.Session():
    input1 = tf.constant([1.0, 1.0, 1.0, 1.0])
    input2 = tf.constant([4.0, 5.0, 6.0, 7.0])
    output = tf.add(input1, input2)
    print("input1: ")
    print(input1)
    print(input1.eval())
    result = output.eval()
    print("result: ", result)

input1: 
Tensor("Const_41:0", shape=(4,), dtype=float32)
[ 1.  1.  1.  1.]
result:  [ 5.  6.  7.  8.]


## Multiple operations


In [19]:
import tensorflow as tf

with tf.Session():
    input1 = tf.constant(1.0, shape=[4])
    input2 = tf.constant(2.0, shape=[4])
    input3 = tf.constant(3.0, shape=[4])
    print("input2")
    print(input2)
    print(input2.eval())
    output = tf.add(tf.add(input1, input2), input3)
    print("output:")
    print(output)
    print(output.eval())
    result = output.eval()
    print("result:")
    print(result)

input2
Tensor("Const_39:0", shape=(4,), dtype=float32)
[ 2.  2.  2.  2.]
output:
Tensor("Add_20:0", shape=(4,), dtype=float32)
[ 6.  6.  6.  6.]
result:
[ 6.  6.  6.  6.]


##  Adding two matrices

In [17]:
import tensorflow as tf
import numpy as np

with tf.Session():
    input1 = tf.constant(1.0, shape=[2, 3])
    input2 = tf.constant(np.reshape(np.arange(1.0, 7.0, dtype=np.float32), (2, 3)))
    print("input1: ")
    print(input1)
    print(input1.eval())
    print("input2: ")
    print(input2)
    print(input2.eval())
    output = tf.add(input1, input2)
    print(output.eval())

input1: 
Tensor("Const_33:0", shape=(2, 3), dtype=float32)
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
input2: 
Tensor("Const_34:0", shape=(2, 3), dtype=float32)
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]]


##  Multiplying matrices


In [15]:
#@test {"output": "ignore"}
import tensorflow as tf
import numpy as np

with tf.Session():
    input_features = tf.constant(np.reshape([1, 0, 0, 1], (1, 4)).astype(np.float32))
    weights = tf.constant(np.random.randn(4, 2).astype(np.float32))
    output = tf.matmul(input_features, weights)
    print("Input:")
    print(input_features.eval())
    print("Weights:")
    print(weights.eval())
    print("Output:")
    print(output.eval())

Input:
[[ 1.  0.  0.  1.]]
Weights:
[[-0.42283544 -1.77805948]
 [ 0.18874162 -0.62736183]
 [-0.70631087  0.28112113]
 [-0.73524332 -0.63260752]]
Output:
[[-1.15807879 -2.41066694]]


## Use of variables


In [39]:
#@test {"output": "ignore"}
import tensorflow as tf
import numpy as np

with tf.Session() as sess:
    # Set up two variables, total and weights, that we'll change repeatedly.
    # original:
    #    total = tf.Variable(tf.zeros([1, 2]))
    total = tf.Variable(tf.ones([1, 2]))
    print("total:")
    print(total)
    print()
    print("I am not able to print the `eval` of total, since it was not (yet) initialized")
    weights = tf.Variable(tf.random_uniform([1,2]))
    
    # Initialize the variables we defined above.
    tf.global_variables_initializer().run()

    print("total")
    print(total.eval())
    print("At this point, after the global_variables_initializer().run() operation, the variables are initialized.")
    print()
    
    # This only adds the operators to the graph right now. The assignment
    # and addition operations are not performed yet.
    update_weights = tf.assign(weights, tf.random_uniform([1, 2], -1.0, 1.0))
    update_total = tf.assign(total, tf.add(total, weights))

    print("update_weights")
    print(update_weights.eval())
    print()

    print("update_total")
    print(update_total.eval())
    print()
    print()

    for _ in range(5):
        # Actually run the operation graph, so randomly generate weights and then
        # add them into the total. Order does matter here. We need to update
        # the weights before updating the total.
        sess.run(update_weights)
        sess.run(update_total)

        print(_)
        print(weights.eval(), total.eval())
        print()


total:
Tensor("Variable_31/read:0", shape=(1, 2), dtype=float32)

I am not able to print the `eval` of total, since it was not (yet) initialized
total
[[ 1.  1.]]
At this point, after the global_variables_initializer().run() operation, the variables are initialized.

update_weights
[[-0.97377563  0.78788519]]

update_total
[[ 0.02622437  1.78788519]]


0
[[ 0.45391965  0.86292505]] [[ 0.48014402  2.65081024]]

1
[[-0.08955789 -0.30757046]] [[ 0.39058614  2.34323978]]

2
[[-0.39798188 -0.63343954]] [[-0.00739574  1.70980024]]

3
[[-0.17250752  0.07714272]] [[-0.17990327  1.78694296]]

4
[[-0.41703868 -0.1711731 ]] [[-0.59694195  1.61576986]]

