In [1]:
import tensorflow as tf
import numpy as np

In [2]:
with tf.Session():
    input1 = tf.constant([1.0, 1.0, 1.0, 1.0])
    input2 = tf.constant([2.0, 2.0, 2.0, 2.0])
    output = tf.add(input1, input2)
    result = output.eval()
    print(result)

[ 3.  3.  3.  3.]


In [3]:
np.ones((4, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

# Multiplying matrices

In [4]:
import tensorflow as tf
import numpy as np

with tf.Session():
    input_features = tf.constant(np.reshape([1, 0, 0, 1], (1, 4)).astype(np.float32))
    weights = tf.constant(np.ones((4, 2)).astype(np.float32))
    output = tf.matmul(input_features, weights)
    print("Input:")
    print(input_features.eval())
    print("Weights:")
    print(weights.eval())
    print("Output:")
    print(output.eval())

Input:
[[ 1.  0.  0.  1.]]
Weights:
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
Output:
[[ 2.  2.]]


# Use of variables

In [15]:
#@test {"output": "ignore"}
import tensorflow as tf
import numpy as np

with tf.Session() as sess:
    # Set up two variables, total and weights, that we'll change repeatedly.
    total = tf.Variable(tf.zeros([1, 2]))
    weights = tf.Variable(tf.random_uniform([1,2]))

    # Initialize the variables we defined above.
    tf.global_variables_initializer().run()

    print("Making clear that we don't run the Tensorflow statements when we go over the line")
    print("We run them with the 'eval' function or with 'sess.run'")
    print("\n")
    print(total)
    print(total.eval())
    print("\n")
    print("\n")
    
    # This only adds the operators to the graph right now. The assignment
    # and addition operations are not performed yet.
    update_weights = tf.assign(weights, tf.random_uniform([1, 2], -1.0, 1.0))
    update_total = tf.assign(total, tf.add(total, weights))
  
    for _ in range(5):
        # Actually run the operation graph, so randomly generate weights and then
        # add them into the total. Order does matter here. We need to update
        # the weights before updating the total.
        sess.run(update_weights)
        sess.run(update_total)
    
        print(weights.eval(), total.eval())

Making clear that we don't run the Tensorflow statements when we go over the line
We run them with the 'eval' function or with 'sess.run'


Tensor("Variable_14/read:0", shape=(1, 2), dtype=float32)
[[ 0.  0.]]




(array([[-0.94827676,  0.48735237]], dtype=float32), array([[-0.94827676,  0.48735237]], dtype=float32))
(array([[ 0.14984369,  0.33222651]], dtype=float32), array([[-0.79843307,  0.81957889]], dtype=float32))
(array([[-0.01295328,  0.79080296]], dtype=float32), array([[-0.81138635,  1.61038184]], dtype=float32))
(array([[-0.95725322,  0.83834505]], dtype=float32), array([[-1.76863956,  2.44872689]], dtype=float32))
(array([[-0.64322996, -0.76451612]], dtype=float32), array([[-2.41186953,  1.68421078]], dtype=float32))
